#+title: Todo

* [ ] General
** [X] Add TUI message plumbing to UIServer
** [X] Add state to UIServer - first message sent to idle state should start the workflow
** [ ] Stream log messages/errors to client. Figure out general startup sequencing and error handling.
** [ ] Fix logging - have a special buffer and a way to see logs at will
** [ ] Create Step renderer in TUI client
** [ ] Add input request stack to TUI
* [ ] Runner
** [X] Add is_complete to Step to differentiate between intermediate and final results
** [X] Add tool support by checking if complete step was received and it contains tool calls
** [X] Create a separate BaseModel for runner generator responses, do not use Step. Convert response to a step.
** [X] Tool rejection might include a message - pass that as a tool response
** [ ] Correctly handle incorrect response to PROMPT
** [ ] Extend PROMPT Step to have mode (message, approval, etc)
* [ ] Migrate tools
** [ ] Patch
** [ ] Shell / Exec
** [ ] TODO
* [ ] Migrate nodes
** [ ] Patch
** [ ] Exec (rename to Shell)
* [ ] UI
** [X] Create an in-memory bidirectional communication channel
** [ ] TUI library
*** [ ] Refactor apply_style
*** [X] Add on_cancel (esc) to SelectList event. Figure out how to handle esc, as it is conflicts with special sequences
*** [X] Remove padding from SelectList
*** [ ] Add toolbar
* [ ] LLM Node
** [ ] Require outcome to be provided and loop until it is provided
* [ ] Fix up TUI tests - need to run Rich in non-terminal mode
