#+title: Todo

* [ ] General
** [X] Add TUI message plumbing to UIServer
** [X] Add state to UIServer - first message sent to idle state should start the workflow
** [ ] Stream log messages/errors to client. Figure out general startup sequencing and error handling.
** [ ] Fix logging - have a special buffer and a way to see logs at will
** [X] Rethink tool step handling. Make it easier for UI to understand the tool execution state
** [X] Create Step renderer in TUI client
** [X] Add input request stack to TUI
** [X] Set input header depending on the top of the input stack
** [ ] Fix APPROVE/DECLINE rendering
** [ ] Fix knowlt summary documentation generation - it adds python docstring twice
** [ ] Add a way for knowlt to return individual symbols from file by id. have compact ids, not uuids
** [ ] Add context compression? How?
* [ ] Runner
** [X] Add is_complete to Step to differentiate between intermediate and final results
** [X] Add tool support by checking if complete step was received and it contains tool calls
** [X] Create a separate BaseModel for runner generator responses, do not use Step. Convert response to a step.
** [X] Tool rejection might include a message - pass that as a tool response
** [ ] Correctly handle incorrect response to PROMPT
** [ ] Extend PROMPT Step to have mode (message, approval, etc)
* [ ] Migrate tools
* [ ] Migrate nodes
* [ ] UI
** [X] Create an in-memory bidirectional communication channel
** [X] History support
- on_history_up, on_history_down events
- history in UIState
- on_submit in UIState forwarded to app.py
** [ ] Command handler
- extend server to support commands
** [ ] Auto-complete support
** [ ] Add toolbar component under input
** [ ] TUI library
*** [X] Refactor apply_style
*** [X] Add on_cancel (esc) to SelectList event. Figure out how to handle esc, as it is conflicts with special sequences
*** [X] Remove padding from SelectList
*** [ ] Add animation support, potentially via Rich Live
*** [ ] Add optimization to not re-render unchanged lines after top-level component if height did not change. Figure out generic algorithm.
*** [ ] Fix up TUI tests - need to run Rich in non-terminal mode
* [ ] LLM Node
** [ ] Require outcome to be provided and loop until it is provided
* [ ] Tools
** [X] Refactor tool registration
** [ ] Simplify error reporting for v4a patch tool
