#+title: Todo

* [ ] General
** [ ] Add support for edge-level state policy override
** [X] Fix component addition/removal for help
** [X] Rework tooltip
** [ ] Benchmark slow apply_patch on Windows
** [ ] Fix rendering full lines - it seems like we're adding delete till end even if line takes whole screen
** [ ] Current context window usage (input) is showing accumulated number instead of last step number
** [ ] Create alternative Markdown renderer that only highlights, but does not format
** [ ] Need apply_patch formatter with input and output (collapsed)
** [ ] Need to rename read_files to read_file
** [ ] Animation stops after showing/hiding toolbar component
** [ ] Figure out how to support parallel nested workflows:
- Remove the single workflow stack or refactor it to contain a list of runners instead of one 
- Figure out how to drive multiple parallel workflow tasks. Multiple coordinators? Single awaitable for results? 
- Figure out how does this change data model (if at all) 
- Figure out how this affects the UI - just change confirmations to be displayed from child workflow and change toolbar around that time?
** [ ] Assign a number to collapse/expand a specific component and show number in the component view. (bad idea due to repaints?)
** [ ] Compact tool call representation, where consequent calls are merged onto a single.
** [ ] Hide time indicator for tool calls - it is not helpful14. Limit number of lines actually rendered for full refreshes, make the number configurable
** [X] Add hidden flag to components to prevent components from being removed from the bottom
** [ ] Combine input + toolbar + help + etc to a single component due to dynamic component shifting
- Move stacking logic out of TUIState
- Move keyboard logic out of TUIState
** [X] When inserting component to a specific position, skip deleted items.
** [ ] ctrl+x followed by c when everything is collapsed prints a line to output for some reason and breaks rendering
** [ ] Figure out how to show input/http_input nodes as a user input (highlight, etc)
** [ ] Figure out why http_input intemediate message is not overridden by new text
- Rework intermediate messages to be complete and not deltas?
** [?] Fix tall input component logic
*** [X] Cap input component height to 70% of the screen
*** [X] Make input component support internal scrolling
*** [ ] If input component is scrolling, show percentage in padding
** [ ] Autocomplete
*** [ ] Figure out why auto-complete might return same file multiple times
*** [ ] Make sure that autocomplete does not interfere with history up
** [ ] Add sync exception handler and send it to the log
** [ ] Add session log renderer as a separate screen + shortcut
** [ ] Need to remove outline from input - it messes up copying
** [ ] Measure and report time it took to run the step at the step bottom.
- Figure out a way to add component under last message and skip it when adding a new step message
** [X] Add /reset command
** [ ] Test multi-screen paste
*** [ ] Handle paste without showing whole content
** [ ] Add a way for knowlt to return individual symbols from file by id.
** [ ] Add collapse/expand for components
*** [ ] Add default setting into node for collapse status and lines.
** [ ] Add input shotcut manager
*** [ ] Keybindings in configuration
*** [ ] Mapping to commands
** [ ] Change auto-complete protocol to also send back cursor position with list of complete options
*** [ ] Do client-side validation or hide auto-complete if user keeps typing
** [ ] Continue after stop needs explicit separator.
** [ ] Show node transitions in the UI?
** [X] Add node visible flag - some are technical and should be hidden from the UI/autocompletion
** [ ] Gemini 3 support
*** [ ] Temperature control
** [ ] Add ctrl+r history search
** [ ] Add context compression? How?
** [ ] Collapse/expand to work with visible components first, then continue going backwards. Keep track of updated components to resume from.
* [ ] Settings
** [ ] Tweak templated nodes
** [ ] Create correct initial templates for chat, coder, architect and agent.
* [ ] Runner
** [ ] Correctly handle incorrect response to PROMPT
* [ ] UI
*** [ ] Rethink TUIState
- Right now heavily dependent on a bunch of callbacks passed from App
- Limited APIs possible
- Consolidate APIs into interface?
** [ ] Hide tool approved events 
** [ ] TUI library
*** [ ] Add optimization to not re-render unchanged lines after top-level component if height did not change. Figure out generic algorithm. Useful for animations.
*** [X] Fix up TUI tests - need to run Rich in non-terminal mode
* [ ] LLM Node
** [ ] Require outcome to be provided and loop until it is provided
* [ ] Tools
** [ ] Simplify error reporting for v4a patch tool
* [ ] System prompts
** [ ] Discovery
*** [ ] Gemini does not use search for some reason, steer towards search
* [ ] Tools
** [ ] Delayed execution tool + executor
* [ ] Session management
** [ ] Branch current session from a specific message
** [ ] Load session from the disk
** [ ] Store session inputs in a metadat file and show them as a summary
* [ ] Patchers
** [ ] More strict V4A parser
*** [ ] Prevent partial updates?
